t_6693/calc/urls.py
from django.urls import path  # type: ignore

from t_6693.calc.views import (  # type: ignore
    Calc_1_PDF_View,
    Calc_1_View,
    Calc_2_PDF_View,
    Calc_2_View,
)

descr = ""

urlpatterns = [
    path("1", Calc_1_View.as_view(), name="calc_1"),
    path("2", Calc_2_View.as_view(), name="calc_2"),
    path(
        f"Описание {descr}",
        Calc_1_PDF_View.as_view(),
        name="calc_1_pdf",
    ),
    path("pdf-2", Calc_2_PDF_View.as_view(), name="calc_2_pdf"),
]

t_6693/comms/urls.py
from django.urls import path  # type: ignore

from t_6693.comms.views import (  # type: ignore
    CommCreateView,
    CommListView,
    CommUpdateView,
)

urlpatterns = [
    path("", CommListView.as_view(), name="comm_list"),
    path("создать/", CommCreateView.as_view(), name="comm_create"),
    path("<int:pk>/изменить/", CommUpdateView.as_view(), name="comm_update"),
]

t_6693/urls.py
from django.contrib import admin  # type: ignore
from django.urls import include, path  # type: ignore

from t_6693 import views  # type: ignore

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('калькулятор/', include('t_6693.calc.urls')),
    path('чбо/', include('t_6693.comms.urls')),
    path('миссия/', include('t_6693.missions.urls')),
    path('вдохновение/', include('t_6693.inspirations.urls')),
    path('совместимость-чбо/', include('t_6693.comps_comms.urls')),
    path('совместимость-миссия/', include('t_6693.comps_miss.urls')),

    path('пользователи/', include('t_6693.users.urls')),
    path('123456/', views.LoginUser.as_view(), name='login'),
    path('выход/', views.LogoutUser.as_view(), name='logout'),
    path("admin/", admin.site.urls),

    path('confirm', views.ConfirmView.as_view(), name='confirm'),
]

t_6693/users/urls.py
from django.urls import path  # type: ignore

from t_6693.users.views import (  # type: ignore
    PasswordUpdateView,
    UserCreateView,
    UserDeleteView,
    UserListView,
    UserUpdateView,
)

urlpatterns = [
    path("", UserListView.as_view(), name="user_list"),
    path("создать/", UserCreateView.as_view(), name="user_create"),
    path("<int:pk>/изменить", UserUpdateView.as_view(), name="user_update"),
    path(
        "сменить-пароль", PasswordUpdateView.as_view(), name="password_update"
    ),
    path("<int:pk>/удалить", UserDeleteView.as_view(), name="user_delete"),
]

t_6693/calc/models.py
# from django.db import models

# Create your models here.

t_6693/comps_comms/models.py
from django.db import models  # type: ignore


class Comp_Comm(models.Model):
    name = models.CharField(
        max_length=2,
        unique=True,
        blank=False,
    )

    descr_1 = models.TextField(
        blank=True,
    )

    descr_2 = models.TextField(
        blank=True,
    )

    def __str__(self):
        return self.id
    
    class Meta:
        ordering = ['name']

t_6693/comps_miss/models.py
from django.db import models  # type: ignore


class Comp_Miss(models.Model):
    name = models.CharField(
        max_length=2,
        unique=True,
        blank=False,
    )

    descr_1 = models.TextField(
        blank=True,
    )

    descr_2 = models.TextField(
        blank=True,
    )

    def __str__(self):
        return self.id

    class Meta:
        ordering = ['name']

t_6693/inspirations/models.py
from django.db import models  # type: ignore


class Inspiration(models.Model):
    descr = models.TextField(
        blank=True,
        unique=True,
    )

    def __str__(self):
        return self.id

    class Meta:
        ordering = ['id']

t_6693/missions/models.py
from django.db import models  # type: ignore


class Mission(models.Model):

    descr = models.TextField(
        blank=True,
        unique=True,
    )

    def __str__(self):
        return self.id

    class Meta:
        ordering = ['id']

t_6693/comms/forms.py
from django.forms import ModelForm  # type: ignore

from t_6693.comms.models import Comm  # type: ignore


class CommForm(ModelForm):
    class Meta:
        model = Comm
        fields = ("id", "max_descr", "min_descr_man", "min_descr_wom")
        labels = {
            "max_descr": "Описание",
            "min_descr_man": "Мужчина",
            "min_descr_wom": "Женщина",
        }

t_6693/comps_comms/forms.py
from django.forms import ModelForm  # type: ignore

from t_6693.comps_comms.models import Comp_Comm  # type: ignore


class Comp_CommForm(ModelForm):
    class Meta:
        model = Comp_Comm
        fields = ("name", "descr_1", "descr_2")
        labels = {
            "name": "Сочетание",
            "descr_1": "Описание Min",
            "descr_2": "Описание Max",
        }

t_6693/calc/views.py
from django.core.cache import cache  # type: ignore
from django.shortcuts import render  # type: ignore
from django.views.generic import TemplateView  # type: ignore
from django_renderpdf.views import PDFView  # type: ignore

from .calc import calc_num, get_comp  # type: ignore
from .forms import CalcForm_1, CalcForm_2


class Calc_1_View(TemplateView):
    template_name = "calc/calc_1.html"

    def get(self, request, *args, **kwargs):
        form = CalcForm_1()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            submitbutton = request.POST.get("submit")
            resetbutton = request.POST.get("reset")

            form = CalcForm_1(request.POST or None)
            if form.is_valid():
                sex = form.cleaned_data.get("sex")
                sex = "Мужчина" if sex == 1 else "Женщина"
                name = form.cleaned_data.get("name")
                bd = form.cleaned_data.get("birthday")
                res = calc_num(bd)
                context = {
                    "form": form,
                    "sex": sex,
                    "name": name,
                    "bd": bd,
                    "res": res,
                    "submitbutton": submitbutton,
                    "resetbutton": resetbutton,
                }
                if request.user.is_authenticated is True:
                    cache.set("status", True)
                else:
                    cache.set("status", False)
                cache.set("sex", sex)
                cache.set("name", name)
                cache.set("bd", bd)
                cache.set("res", res)
                return render(request, self.template_name, context)
        else:
            form = CalcForm_1()
        return render(request, self.template_name, {"form": form})


class Calc_1_PDF_View(PDFView):
    template_name = "calc/calc_1_pdf.html"

    def get_context_data(self):
        context = {
            "status": cache.get("status"),
            "sex": cache.get("sex"),
            "name": cache.get("name"),
            "bd": cache.get("bd"),
            "res": cache.get("res"),
            }
        return context


class Calc_2_View(TemplateView):
    template_name = "calc/calc_2.html"

    def get(self, request, *args, **kwargs):
        form = CalcForm_2()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            submitbutton = request.POST.get("submit")
            resetbutton = request.POST.get("reset")

            form = CalcForm_2(request.POST or None)
            if form.is_valid():
                name_1 = form.cleaned_data.get("name_1")
                name_1 = "Партнёр 1" if name_1 == "" else name_1
                name_2 = form.cleaned_data.get("name_2")
                name_2 = "Партнёр 2" if name_2 == "" else name_2
                bd_1 = form.cleaned_data.get("birthday_1")
                bd_2 = form.cleaned_data.get("birthday_2")
                res_1 = calc_num(bd_1)
                res_2 = calc_num(bd_2)
                res_comp_comm = (
                    ""
                    if res_1["comm"] is None or res_2["comm"] is None
                    else get_comp(str(res_1["comm"].id) + str(res_2["comm"].id))
                )
                res_comp_miss = (
                    ""
                    if res_1["miss"] is None or res_2["miss"] is None
                    else get_comp(str(res_1["miss"].id) + str(res_2["miss"].id))
                )
                context = {
                    "form": form,
                    "name_1": name_1,
                    "name_2": name_2,
                    "res_1": res_1,
                    "res_2": res_2,
                    "res_comp_comm": res_comp_comm,
                    "res_comp_miss": res_comp_miss,
                    "submitbutton": submitbutton,
                    "resetbutton": resetbutton,
                }
                if request.user.is_authenticated is True:
                    cache.set("status", True)
                else:
                    cache.set("status", False)
                cache.set("name_1", name_1)
                cache.set("name_2", name_2)
                cache.set("res_1", res_1)
                cache.set("res_2", res_2)
                cache.set("res_comp_comm", res_comp_comm)
                cache.set("res_comp_miss", res_comp_miss)
                return render(request, self.template_name, context)
        else:
            form = CalcForm_2()
        return render(request, self.template_name, {"form": form})


class Calc_2_PDF_View(PDFView):
    template_name = "calc/calc_2_pdf.html"

    def get_context_data(self):
        context = {
            "status": cache.get("status"),
            "name_1": cache.get("name_1"),
            "name_2": cache.get("name_2"),
            "res_1": cache.get("res_1"),
            "res_2": cache.get("res_2"),
            "res_comp_comm": cache.get("res_comp_comm"),
            "res_comp_miss": cache.get("res_comp_miss"),
            }
        return context

t_6693/comms/views.py
from django.contrib.messages.views import SuccessMessageMixin  # type: ignore
from django.urls import reverse_lazy  # type: ignore
from django.views.generic import (  # type: ignore
    CreateView,
    ListView,
    UpdateView,
)

from t_6693.comms.forms import CommForm  # type: ignore
from t_6693.comms.models import Comm  # type: ignore
from t_6693.mixins import ProjectLoginRequiredMixin  # type: ignore


class CommCreateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, CreateView
):
    model = Comm
    form_class = CommForm
    template_name = "object.html"
    success_url = reverse_lazy("comm_list")
    success_message = "Запись успешно создана"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Создать ЧБО"
        context["button_text"] = "Создать"
        context["object"] = Comm.objects.count() + 1
        # context["ur"] = "url 'comm_create'"
        return context


class CommListView(ProjectLoginRequiredMixin, ListView):
    model = Comm
    template_name = "comms/comms.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model"] = "Comm"
        context["title"] = "Число Близкого Общения"
        context["rec_count"] = Comm.objects.count()
        context["rec_limit"] = 9
        context["result"] = Comm.objects.all
        return context


class CommUpdateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Comm
    form_class = CommForm
    template_name = "object.html"
    success_url = reverse_lazy("comm_list")
    success_message = "Запись успешно изменена"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Изменить ЧБО"
        context["button_text"] = "Изменить"
        context["object"] = self.object.id
        return context

t_6693/comps_comms/views.py
from django.contrib.messages.views import SuccessMessageMixin  # type: ignore
from django.urls import reverse_lazy  # type: ignore
from django.views.generic import (  # type: ignore
    CreateView,
    ListView,
    UpdateView,
)

from t_6693.comps_comms.forms import Comp_CommForm  # type: ignore
from t_6693.comps_comms.models import Comp_Comm  # type: ignore
from t_6693.mixins import ProjectLoginRequiredMixin  # type: ignore


class Comp_CommListView(ProjectLoginRequiredMixin, ListView):
    model = Comp_Comm
    template_name = "comps_comms/comps_comms.html"
    # context_object_name = "comps_comms"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model"] = "Comp_Comm"
        context["title"] = "Совместимость по ЧБО"
        context["rec_count"] = Comp_Comm.objects.count()
        context["rec_limit"] = 45
        context["result"] = Comp_Comm.objects.all
        return context


class Comp_CommCreateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, CreateView
):
    model = Comp_Comm
    form_class = Comp_CommForm
    template_name = "object.html"
    success_url = reverse_lazy("comp_comm_list")
    success_message = "Запись успешно создана"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Создать Совместимость по ЧБО"
        context["button_text"] = "Создать"
        return context


class Comp_CommUpdateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Comp_Comm
    form_class = Comp_CommForm
    template_name = "object.html"
    success_url = reverse_lazy("comp_comm_list")
    success_message = "Запись успешно изменена"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Изменить Совместимость по ЧБО"
        context["button_text"] = "Изменить"
        context["object"] = self.object.name
        return context

t_6693/comps_miss/views.py
from django.contrib.messages.views import SuccessMessageMixin  # type: ignore
from django.urls import reverse_lazy  # type: ignore
from django.views.generic import (  # type: ignore
    CreateView,
    ListView,
    UpdateView,
)

from t_6693.comps_miss.forms import Comp_MissForm  # type: ignore
from t_6693.comps_miss.models import Comp_Miss  # type: ignore
from t_6693.mixins import ProjectLoginRequiredMixin  # type: ignore


class Comp_MissListView(ProjectLoginRequiredMixin, ListView):
    model = Comp_Miss
    template_name = "comps_miss/comps_miss.html"
    # context_object_name = "comps_miss"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model"] = "Comp_Miss"
        context["title"] = "Совместимость по Миссии"
        context["rec_count"] = Comp_Miss.objects.count()
        context["rec_limit"] = 45
        context["result"] = Comp_Miss.objects.all
        return context


class Comp_MissCreateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, CreateView
):
    model = Comp_Miss
    form_class = Comp_MissForm
    template_name = "object.html"
    success_url = reverse_lazy("comp_miss_list")
    success_message = "Запись успешно создана"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Создать Совместимость по Миссии"
        context["button_text"] = "Создать"
        return context


class Comp_MissUpdateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Comp_Miss
    form_class = Comp_MissForm
    template_name = "object.html"
    success_url = reverse_lazy("comp_miss_list")
    success_message = "Запись успешно изменена"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Изменить Совместимость по Миссии"
        context["button_text"] = "Изменить"
        context["object"] = self.object.name
        return context

t_6693/inspirations/views.py
from django.contrib.messages.views import SuccessMessageMixin  # type: ignore
from django.urls import reverse_lazy  # type: ignore
from django.views.generic import (  # type: ignore
    CreateView,
    ListView,
    UpdateView,
)

from t_6693.inspirations.forms import InspirationForm  # type: ignore
from t_6693.inspirations.models import Inspiration  # type: ignore
from t_6693.mixins import ProjectLoginRequiredMixin  # type: ignore


class InspirationCreateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, CreateView
):
    model = Inspiration
    form_class = InspirationForm
    template_name = "object.html"
    success_url = reverse_lazy("inspiration_list")
    success_message = "Запись успешно создана"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Создать Вдохновение"
        context["button_text"] = "Создать"
        context["object"] = Inspiration.objects.count() + 1
        return context


class InspirationListView(ProjectLoginRequiredMixin, ListView):
    model = Inspiration
    template_name = "inspirations/inspirations.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model"] = "Inspiration"
        context["title"] = "Вдохновение"
        context["rec_count"] = Inspiration.objects.count()
        context["rec_limit"] = 22
        context["result"] = Inspiration.objects.all
        return context


class InspirationUpdateView(
    ProjectLoginRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Inspiration
    form_class = InspirationForm
    template_name = "object.html"
    success_url = reverse_lazy("inspiration_list")
    success_message = "Запись успешно изменена"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Изменить Вдохновение"
        context["button_text"] = "Изменить"
        context["object"] = self.object.id
        return context
    

t_6693/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>t-6693</title>
</head>

<body class="container d-flex flex-column min-vh-100">

  <header class="d-flex justify-content-center py-3">

    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light bg-light ms-3">

        <a class="navbar-brand" href="{% url 'index' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="24" fill="currentColor"
            class="bi bi-house align-text-top" viewBox="0 0 16 16">
            <path
              d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z" />
          </svg>
          Главная
        </a>

        <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggleExternalContent">

          <ul class="navbar-nav mr-auto">

            <li class="nav-item"">
              <a class=" nav-link" href="{% url 'calc_1' %}">Калькулятор-1</a>
            </li>

            <li class="nav-item"">
              <a class=" nav-link" href="{% url 'calc_2' %}">Калькулятор-2</a>
            </li>

            {% if user.is_authenticated %}

            <li class="nav-item"">
            <a class=" nav-link" href="{% url 'comm_list' %}">ЧБО</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'mission_list' %}">Миссия</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'inspiration_list' %}">Вдохновение</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'comp_comm_list' %}">Совм-ЧБО</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'comp_miss_list' %}">Совм-Миссия</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'user_list' %}">Пользователи</a>
            </li>

            <li class="nav-item">
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <input class="btn nav-link" type="submit" value='Выход'>
              </form>
            </li>

            {% else %}

            <!-- <li class="nav-item">
              <form method="post">
                {% csrf_token %}
                <a class="nav-link" href="{% url 'login' %}">Вход</a>
              </form>
            </li>

            <li class="nav-item">
              <form method="post">
                {% csrf_token %}
                <a class="nav-link" href="{% url 'user_create' %}">Регистрация</a>
              </form>
            </li> -->

            {% endif %}

          </ul>

        </div>

      </nav>

    </div>

  </header>

  {% bootstrap_messages %}

  <div class="container wrapper flex-grow-1">
    {% block content %}{% endblock %}
  </div>

  <footer>
    <div class="container my-5 pt-4 border-top">
    </div>
  </footer>

</body>

</html>

t_6693/templates/calc.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

<h1 class="my-4">{% block title %}{% endblock %}</h1>
<form method="POST" action="#"">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" name="submit" value="Рассчитать">
  <input class="btn btn-outline-warning" type="submit" value="Очистить">
</form>
<br>

{% if submitbutton == "Рассчитать" %}
{% block form %}{% endblock %}
{% endif %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

{% endblock %}

t_6693/templates/confirm.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

<div class="bs-example">
  <div id="confirmModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body d-flex justify-content-center">
          <h5 class="modal-title">Подтвердите</h5>
        </div>
        <div class="modal-footer d-flex justify-content-around">

          <a href="{% url 'comm_list' %}" type="button" class="btn btn-warning">Отменить</a>
          <form method="get" action="{% url 'comm_list' %}">
            <button id="Save" type="submit" class="btn btn-primary" data-dismiss="modal">{{ button_text }}</button>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<script>
  $(document).ready(function () {
    $("#confirmModal").on('shown.bs.modal', function () {
      $(this).find('#Save').focus();
    });
  });
</script>
<style>
  .bs-example {
    margin: 20px;
  }
</style>

t_6693/templates/delete.html
{% extends 'base.html' %}

{% block content %}

<h1 class="my-4">{% block heading %}{% endblock %}</h1>

<form method="post">
    {% csrf_token %}
    <p>Подтвердите удаление записи для {% block object_name %}{% endblock %}</p>
    <input class="btn btn-outline-danger" type="submit" value="Да, удалить">
  </form>

{% endblock %}

t_6693/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
  <div class="card-body p-5 bg-light">

    <div class="display-6">Калькуляторы</div>
    <p class="lead">Выберите вариант</p>
    <hr>

    <div class="container d-flex justify-content-left">
      <a class="btn btn-outline-primary btn-lg" href="{% url 'calc_1' %}">Личный</a>
    </div>
    <br>
    <div class="container d-flex justify-content-left">
      <a class="btn btn-outline-primary btn-lg" href="{% url 'calc_2' %}">Совместимость</a>
    </div>

  </div>
</div>
</div>

{% endblock %}

t_6693/templates/list.html
{% extends 'base.html' %}

{% block content %}
<h1 class="my-4">{{ title }}</h1>
{% if rec_count < rec_limit %} <a class="btn btn-primary" href="{% block href_create %}{% endblock %}">
  Создать</a>{%endif %}

  <table class="table table-striped table-hover table-borderless my-4">
    <thead align="center" class="thead-dark bg-warning" style="--bs-bg-opacity: .5;">
      <tr>
        {% block th %}{% endblock %}
      </tr>
    </thead>
    <tbody>
      {% if result %}
      {% for res in result %}
      <tr>
        {% block td %}{% endblock %}
        <td>
          <a href="{% block href_update %}{% endblock %}">Изменить</a>
          {% if title == "Пользователи" %}
          <br>
          <a href="{% block href_delete %}{% endblock %}">Удалить</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <tr>
        <td colspan="7">
          Записей пока нет
        </td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  {% endblock %}

t_6693/templates/object.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

<h1 class="my-4"> {{ title }} {{ object }} </h1>

<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary" type="submit" value={{button_text}}>
  <br><br>
  {% if title == "Изменить Пользователя" %}
  <a class="btn btn-outline-warning" href="{% url 'password_update' %}">Сменить пароль</a>
  {% endif %}
</form>

{% endblock %}

<!-- <form method="post" action="{% url 'confirm' %}"> -->
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmModal">{{ button_text }}</button>
{% include 'confirm.html' %} -->

t_6693/templates/popup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<div class="bs-example">
  <!-- Button HTML (to Trigger Modal) -->
  <a href="#myModal" class="btn btn-lg btn-primary" data-toggle="modal">Сохранить</a>

  <!-- Modal HTML -->
  <div id="myModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body d-flex justify-content-center">
          <h5 class="modal-title">Подтвердите</h5>
        </div>
        <div class="modal-footer d-flex justify-content-around">
          <button type="button" class="btn btn-warning" data-dismiss="modal">Отменить | Ecs</button>
          <button type="button" class="btn btn-primary" id="save">Сохранить</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script>
  $(document).ready(function () {
    $("#myModal").on('shown.bs.modal', function () {
      $(this).find('button[id="save"]').focus();
    });
  });
</script>
<style>
  .bs-example {
    margin: 20px;
  }
</style>
{% endblock %}